# Global settings
[build]
  command = "ng build"
  publish = "dist/drag"

# Redirects and Headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

